### ISSUE TITLE
react app created by create-single-spa not working

### ISSUE THREAD

**Issue by joeldenning** [single-spa/single-spa-playground#17]
![Screen Shot 2020-03-09 at 3 00 28 AM](https://user-images.githubusercontent.com/5524384/76170759-8bd9c380-614a-11ea-889f-bc050180640e.png)

Reported by Steve Back

**Comment by Sauloxd** [comment]
I managed to reproduce this bug on single-spa apps with `/` somewhere in the appName (ex: `@react-mf/people`).
I think the culprit is how the ":appName" is handled in react router:
**Dynamic route for test app definition**
``` js
 <Route path="/app/:appName" component={TestApp} />
```
**How links to this route is being generated**
```
<Link
  to={`/app/${applications[0].name}`}
  className="primary button"
>
  Next step: test it out
</Link>
```
Interpolating the `to` prop will result in `/app/@react-mf/people` where :appName will be mapped to `@react-mf` instead of `@react-mf/people` which is actually defined in the `import-map`!
My proposed solution is to URI encode this appName and decode when TestApp page needs to get the appName from URL

**Comment by joeldenning** [comment]
👍 thanks for the fix.
