### ISSUE TITLE
How to fill in the imports in the import map

### ISSUE THREAD

**Issue by xuoutput** [single-spa/single-spa-playground#34]
After `npx create-single-spa`

![image](https://user-images.githubusercontent.com/16385443/92368486-61cd8200-f12a-11ea-966c-3d627dc9a045.png)

click
**`http://single-spa-playground.org/playground/instant-test?name=@single-spa/add-react&url=8500 `**

it is ok.

then I modify some code

![image](https://user-images.githubusercontent.com/16385443/92368741-b2dd7600-f12a-11ea-9926-202a34de87e6.png)

alright
![image](https://user-images.githubusercontent.com/16385443/92368789-c092fb80-f12a-11ea-9772-cd0375992ac1.png)

But how should I pass this step.

![image](https://user-images.githubusercontent.com/16385443/92368340-2df25c80-f12a-11ea-897e-49d7b0f4b0c4.png)

what's meaning Download URL?
 
![image](https://user-images.githubusercontent.com/16385443/92369017-0d76d200-f12b-11ea-8607-ca09a23bb32d.png)

![image](https://user-images.githubusercontent.com/16385443/92369431-968e0900-f12b-11ea-95c5-bdfc905eafc7.png)

**Comment by joeldenning** [comment]
Hi @xuoutput, apologies for the slow response here. The following part of your screenshot looks weird, and potentially a bug in single-spa-playground:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/5524384/92677497-3ccf3f80-f2e1-11ea-860a-bf3e8ab67e26.png">

The url in that import map should not point to single-spa-playground.org, but rather to localhost:8500

The next step I'd take to diagnose the issue is check the Network tab in your devtools for a request to localhost:8500. Is one of them failing? Is CORS failing? If you open up the URL in its own browser tab, does it show a javascript file?

**Comment by Zhwt** [comment]
@xuoutput Try replacing the `//localhost:8500/...` part in the `Download URL` field with `//127.0.0.1:8500/...` then refresh the playground page. I also experienced this problem with Firefox, it will send request to `https://localhost` then fail with no reason no matter the cert is correct or not.
